import { ReturnCodeFamily } from '../../../src'

export enum HttpShimCodeEnum {
    CACHE_DATA_FETCH_FAILED,
    ACCESSOR_HEADER_NOT_FOUND,
    ACCESSOR_BAD_FORMAT,
    NO_ACCESSOR,
    ENCRYPTED_OP_NO_SECURE_PAYLOAD,
    ENCRYPTED_OP_PATH_NOT_FOUND,
    ENCRYPTED_OP_METHOD_NOT_FOUND,
    ENCRYPTED_OP_NON_JSON_PAYLOAD,
    SECURE_CHANNEL_NOT_FOUND,
    HTTP_SERVER_NOT_INITIALIZED,
    HTTP_SERVER_UNHANDLED_EXCEPTION,
    HTTP_SERVER_ONBEFORE_ERROR,
    HTTP_SERVER_ONAFTER_ERROR,
    HTTP_SERVER_OP_WITH_NO_RETURN,
    HTTP_SERVER_ONBEFORE_BLOCKS_REQ,
    AUTH_HEADER_NOT_FOUND,
    AUTH_HEADER_NOT_VALID,
    AUTH_HEADER_CUSTOM_HANDLER_ERROR,
    AUTH_HEADER_TOKEN_ROLE_UNAUTHORZIED_FOR_API,
    AUTH_HEADER_SIGNED_BUT_PUBLIC_KEY_NOT_FOUND,
    AUTH_HEADER_SIGNED_NO_ROLES_MAP,
    AUTH_HEADER_SIGNED_ROLE_UNAUTHORZIED_FOR_API,
    AUTH_HEADER_SIGNED_BUT_API_DENIES_ALL,
}
export const HttpShimCode = ReturnCodeFamily('HttpShimCode', HttpShimCodeEnum)
